/**
 * Populate a throwaway test with synthetic traffic so the dashboard can be
 * judged before any real data exists.
 *
 *   node scripts/seed-demo.mjs          # create/refresh the demo test
 *   node scripts/seed-demo.mjs --purge  # delete it and everything under it
 *
 * Writes under its own key, never pdp_redesign_2607, so the real test cannot
 * be contaminated by numbers that were invented.
 */

import "dotenv/config";
import { PrismaClient } from "@prisma/client";

const KEY = "demo_do_not_trust";
const db = new PrismaClient();

if (process.argv.includes("--purge")) {
  await db.abTest.deleteMany({ where: { key: KEY } });
  console.log(`purged ${KEY} (events and orders cascade)`);
  await db.$disconnect();
  process.exit(0);
}

// Rates chosen to sit near the store's real numbers: ~1.5% purchase, a
// mid-single-digit add-to-cart rate, and a genuine but modest lift on B. The
// point is to exercise every state the dashboard can render, not to predict.
const DAYS = 14;
const VISITORS_PER_DAY = 3570;
const RATES = {
  a: { add_to_cart: 0.062, initiate_checkout: 0.031, purchase: 0.0146 },
  b: { add_to_cart: 0.070, initiate_checkout: 0.034, purchase: 0.0155 },
};

const startedAt = new Date(Date.now() - DAYS * 864e5);

await db.abTest.deleteMany({ where: { key: KEY } });
await db.abTest.create({
  data: {
    key: KEY,
    name: "DEMO — synthetic data, not a real test",
    hypothesis:
      "Synthetic traffic generated by scripts/seed-demo.mjs so the dashboard can be reviewed before the real test starts. Every number here is invented. Delete with --purge.",
    primaryMetric: "add_to_cart",
    plannedDays: 21,
    startedAt,
    endsAt: new Date(startedAt.getTime() + 21 * 864e5),
  },
});

// Deterministic PRNG (mulberry32) so re-running produces the same dashboard —
// a demo whose numbers move on every refresh is impossible to review against.
let seed = 0x9e3779b9;
const rand = () => {
  seed |= 0; seed = (seed + 0x6d2b79f5) | 0;
  let t = Math.imul(seed ^ (seed >>> 15), 1 | seed);
  t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
  return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
};

const events = [];
const orders = [];
let vid = 0;

for (let day = 0; day < DAYS; day++) {
  const dayStart = startedAt.getTime() + day * 864e5;
  for (let i = 0; i < VISITORS_PER_DAY; i++) {
    const bucket = rand() < 0.5 ? "a" : "b";
    const r = RATES[bucket];
    const visitorId = `demo-${vid++}`;
    const at = new Date(dayStart + rand() * 864e5);

    events.push({ test: KEY, bucket, visitorId, event: "exposure", path: "/products/demo", template: "template-product", createdAt: at });

    // Nested, not independent: you cannot check out without adding to cart.
    if (rand() < r.add_to_cart) {
      events.push({ test: KEY, bucket, visitorId, event: "add_to_cart", path: "/products/demo", template: "template-product", createdAt: at });
      if (rand() < r.initiate_checkout / r.add_to_cart) {
        events.push({ test: KEY, bucket, visitorId, event: "initiate_checkout", path: "/cart", template: "template-cart", createdAt: at });
        if (rand() < r.purchase / r.initiate_checkout) {
          orders.push({
            id: `gid://shopify/Order/demo-${visitorId}`,
            test: KEY, bucket, orderName: `#D${vid}`, visitorId,
            totalPrice: (rand() < 0.25 ? 132 : 48).toFixed(2),
            currency: "USD", placedAt: at,
          });
        }
      }
    }
  }
}

for (let i = 0; i < events.length; i += 5000) {
  await db.abEvent.createMany({ data: events.slice(i, i + 5000), skipDuplicates: true });
}
for (let i = 0; i < orders.length; i += 5000) {
  await db.abOrder.createMany({ data: orders.slice(i, i + 5000), skipDuplicates: true });
}

console.log(`seeded ${KEY}`);
console.log(`  ${events.length.toLocaleString()} events, ${orders.length.toLocaleString()} orders, ${DAYS} days`);
console.log(`\nView at /?test=${KEY} — purge with: node scripts/seed-demo.mjs --purge`);
await db.$disconnect();
